[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[build]
# target = ["riscv32imc-esp-espidf", "x86_64-unknown-linux-gnu"]
target = "riscv32imc-esp-espidf"
# target = "x86_64-unknown-linux-gnu"

[alias]
run_linux = "run --target x86_64-unknown-linux-gnu --bin"
run_esp = "espflash flash --monitor --target riscv32imc-esp-espidf --bin"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v5.2"
